INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('What does CSS stand for?',
'Cascading Style Sheets',
'Computer Style Sheets',
'Creative Style Sheets',
'Colorful Style Sheets',
'A', 'CSS', 'Easy'),

('Which HTML tag is commonly used to link an external CSS file?',
'<css>',
'<style>',
'<link>',
'<stylesheet>',
'C', 'CSS', 'Easy'),

('Which CSS property is used to change text color?',
'font-color',
'text-color',
'color',
'foreground',
'C', 'CSS', 'Easy'),

('Which CSS property is used to change the background color?',
'background-color',
'bg-color',
'color-background',
'background',
'A', 'CSS', 'Easy'),

('Which property is used to change the font size?',
'text-size',
'font-size',
'size',
'font',
'B', 'CSS', 'Easy'),

('Which property is used to make text bold?',
'font-weight',
'text-bold',
'font-style',
'bold',
'A', 'CSS', 'Easy'),

('Which property is used to align text?',
'text-align',
'align-text',
'text-position',
'font-align',
'A', 'CSS', 'Easy'),

('Which value centers text horizontally?',
'left',
'right',
'center',
'middle',
'C', 'CSS', 'Easy'),

('Which CSS property changes the typeface of text?',
'font-family',
'text-family',
'font-type',
'typeface',
'A', 'CSS', 'Easy'),

('Which property is used to make text italic?',
'font-style',
'text-style',
'font-italic',
'italic',
'A', 'CSS', 'Easy'),

('Which property controls the space outside an element?',
'padding',
'margin',
'border',
'spacing',
'B', 'CSS', 'Easy'),

('Which property controls the space inside an element?',
'margin',
'padding',
'border',
'inner-space',
'B', 'CSS', 'Easy'),

('Which property is used to add a border around an element?',
'outline',
'border',
'box-border',
'line',
'B', 'CSS', 'Easy'),

('Which CSS property controls the width of an element?',
'element-width',
'width',
'size',
'length',
'B', 'CSS', 'Easy'),

('Which CSS property controls the height of an element?',
'element-height',
'height',
'size',
'length',
'B', 'CSS', 'Easy');

INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('Which CSS property is used to make an element invisible while keeping its space?',
'display: none',
'visibility: hidden',
'opacity: 0',
'hidden: true',
'B', 'CSS', 'Medium'),

('Which property completely removes an element from the page layout?',
'visibility: hidden',
'display: none',
'opacity: 0',
'remove: true',
'B', 'CSS', 'Easy'),

('Which CSS property is used to control the transparency of an element?',
'transparent',
'opacity',
'visibility',
'alpha',
'B', 'CSS', 'Easy'),

('Which property is used to change the position of an element?',
'position',
'location',
'place',
'position-type',
'A', 'CSS', 'Easy'),

('Which position value keeps an element fixed relative to the viewport?',
'absolute',
'relative',
'fixed',
'static',
'C', 'CSS', 'Easy'),

('Which position value positions an element relative to its nearest positioned ancestor?',
'fixed',
'absolute',
'static',
'sticky-only',
'B', 'CSS', 'Medium'),

('Which CSS property controls the stacking order of elements?',
'stack',
'z-index',
'layer',
'order',
'B', 'CSS', 'Medium'),

('Which CSS property is used to create rounded corners?',
'corner-radius',
'border-radius',
'round-border',
'border-round',
'A', 'CSS', 'Easy'),

('Which CSS property adds a shadow around a box?',
'box-shadow',
'element-shadow',
'border-shadow',
'shadow-box',
'A', 'CSS', 'Easy'),

('Which property adds a shadow to text?',
'font-shadow',
'text-shadow',
'letter-shadow',
'word-shadow',
'B', 'CSS', 'Easy'),

('Which CSS property controls how content that overflows an element is handled?',
'overflow',
'content-flow',
'over-content',
'flow',
'A', 'CSS', 'Easy'),

('Which value of overflow hides content outside the element?',
'visible',
'hidden',
'none',
'clip-content',
'B', 'CSS', 'Easy'),

('Which CSS property is used to set the display behavior of an element?',
'display',
'visibility',
'layout',
'element-type',
'A', 'CSS', 'Easy'),

('Which display value makes an element a flex container?',
'display: block',
'display: flex',
'display: inline',
'display: grid',
'B', 'CSS', 'Easy'),

('Which display value creates a grid container?',
'display: table',
'display: grid',
'display: flexbox',
'display: layout',
'B', 'CSS', 'Easy');

INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('Which CSS property is used to set the space between flex items?',
'gap',
'space',
'flex-space',
'item-gap',
'A', 'CSS', 'Easy'),

('Which property controls the direction of flex items?',
'flex-direction',
'flex-flow-direction',
'direction',
'item-direction',
'A', 'CSS', 'Easy'),

('Which flex-direction value arranges items horizontally from left to right?',
'column',
'row',
'row-reverse',
'horizontal',
'B', 'CSS', 'Easy'),

('Which CSS property aligns flex items along the main axis?',
'align-items',
'justify-content',
'flex-align',
'content-align',
'B', 'CSS', 'Medium'),

('Which CSS property aligns flex items along the cross axis?',
'justify-content',
'align-items',
'flex-align',
'cross-align',
'B', 'CSS', 'Medium'),

('Which property is used to define grid columns?',
'grid-columns',
'grid-template-columns',
'columns',
'grid-column-size',
'B', 'CSS', 'Medium'),

('Which property is used to define grid rows?',
'grid-template-rows',
'grid-rows',
'rows',
'grid-row-size',
'A', 'CSS', 'Medium'),

('Which CSS unit is relative to the font size of the element?',
'px',
'em',
'vh',
'%',
'B', 'CSS', 'Easy'),

('Which CSS unit is relative to the root element font size?',
'em',
'rem',
'px',
'vh',
'B', 'CSS', 'Easy'),

('Which unit represents a percentage of the viewport width?',
'vw',
'vh',
'%',
'vmin',
'A', 'CSS', 'Easy'),

('Which unit represents a percentage of the viewport height?',
'vw',
'vh',
'em',
'rem',
'B', 'CSS', 'Easy'),

('Which pseudo-class applies a style when the mouse is over an element?',
':click',
':hover',
':mouse',
':over',
'B', 'CSS', 'Easy'),

('Which pseudo-class selects the first child of an element?',
':first',
':first-child',
':child-first',
':first-element',
'B', 'CSS', 'Easy'),

('Which pseudo-class applies styles to an element when it receives focus?',
':active',
':focus',
':selected',
':input',
'B', 'CSS', 'Easy'),

('Which pseudo-element is used to insert content before an element?',
'::before',
'::start',
'::first',
'::prepend',
'A', 'CSS', 'Medium'),

('Which pseudo-element is used to insert content after an element?',
'::after',
'::end',
'::last',
'::append',
'A', 'CSS', 'Medium'),

('Which selector targets all elements on a page?',
'#',
'.',
'*',
'@',
'C', 'CSS', 'Easy'),

('Which selector targets an element by its ID?',
'.',
'#',
'*',
'@',
'B', 'CSS', 'Easy'),

('Which selector targets elements by their class?',
'#',
'.',
'*',
'@',
'B', 'CSS', 'Easy'),

('Which CSS property is used to control the order of flex items?',
'flex-order',
'order',
'item-order',
'position-order',
'B', 'CSS', 'Medium');