INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('What does HTML stand for?',
'Hyper Text Markup Language',
'High Text Machine Language',
'Hyperlink Text Markup Language',
'Home Tool Markup Language',
'A', 'HTML', 'Easy'),

('Which tag is used to create the largest heading?',
'<h6>',
'<heading>',
'<h1>',
'<head>',
'C', 'HTML', 'Easy'),

('Which tag is used to create a paragraph?',
'<para>',
'<p>',
'<paragraph>',
'<text>',
'B', 'HTML', 'Easy'),

('Which tag is used to create a hyperlink?',
'<link>',
'<a>',
'<href>',
'<url>',
'B', 'HTML', 'Easy'),

('Which attribute specifies the URL of a hyperlink?',
'src',
'link',
'href',
'url',
'C', 'HTML', 'Easy'),

('Which tag is used to display an image?',
'<image>',
'<img>',
'<picture>',
'<src>',
'B', 'HTML', 'Easy'),

('Which attribute specifies the image path?',
'href',
'src',
'path',
'link',
'B', 'HTML', 'Easy'),

('Which tag creates an unordered list?',
'<ol>',
'<list>',
'<ul>',
'<li>',
'C', 'HTML', 'Easy'),

('Which tag creates an ordered list?',
'<ul>',
'<ol>',
'<li>',
'<order>',
'B', 'HTML', 'Easy'),

('Which tag defines a list item?',
'<item>',
'<list>',
'<li>',
'<ul>',
'C', 'HTML', 'Easy'),

('Which tag is used to create a table?',
'<table>',
'<tab>',
'<tbl>',
'<grid>',
'A', 'HTML', 'Easy'),

('Which tag defines a table row?',
'<td>',
'<tr>',
'<row>',
'<th>',
'B', 'HTML', 'Easy'),

('Which tag defines a table header cell?',
'<td>',
'<header>',
'<th>',
'<thead>',
'C', 'HTML', 'Easy'),

('Which tag defines a table data cell?',
'<data>',
'<td>',
'<cell>',
'<tr>',
'B', 'HTML', 'Easy'),

('Which tag is used to create a form?',
'<input>',
'<form>',
'<field>',
'<formdata>',
'B', 'HTML', 'Easy');

INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('Which tag is used to create a text input field?',
'<text>',
'<input>',
'<textfield>',
'<inputtext>',
'B', 'HTML', 'Easy'),

('Which attribute specifies the type of an input field?',
'kind',
'type',
'inputtype',
'format',
'B', 'HTML', 'Easy'),

('Which input type is used for a password?',
'text',
'secure',
'password',
'hidden',
'C', 'HTML', 'Easy'),

('Which input type is used to select a single option?',
'check',
'radio',
'select',
'option',
'B', 'HTML', 'Easy'),

('Which input type allows multiple selections?',
'radio',
'checkbox',
'multiple',
'select',
'B', 'HTML', 'Easy'),

('Which tag creates a dropdown list?',
'<dropdown>',
'<select>',
'<option>',
'<list>',
'B', 'HTML', 'Easy'),

('Which tag defines an option inside a dropdown?',
'<choice>',
'<select>',
'<option>',
'<item>',
'C', 'HTML', 'Easy'),

('Which attribute makes an input field mandatory?',
'validate',
'required',
'mandatory',
'needed',
'B', 'HTML', 'Easy'),

('Which tag is used to insert a line break?',
'<break>',
'<br>',
'<lb>',
'<newline>',
'B', 'HTML', 'Easy'),

('Which tag creates a horizontal line?',
'<line>',
'<hr>',
'<horizontal>',
'<border>',
'B', 'HTML', 'Easy'),

('Which tag is used to define the document title?',
'<title>',
'<head>',
'<name>',
'<heading>',
'A', 'HTML', 'Easy'),

('Where is the <title> tag placed?',
'<body>',
'<footer>',
'<head>',
'<html>',
'C', 'HTML', 'Easy'),

('Which tag contains the visible content of an HTML page?',
'<head>',
'<body>',
'<main>',
'<content>',
'B', 'HTML', 'Easy'),

('Which declaration specifies that the document uses HTML5?',
'<html5>',
'<doctype html>',
'<!DOCTYPE html>',
'<html version="5">',
'C', 'HTML', 'Easy'),

('Which attribute provides alternative text for an image?',
'title',
'alt',
'text',
'description',
'B', 'HTML', 'Easy');

INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('Which HTML tag is used to define important text?',
'<important>',
'<strong>',
'<bold>',
'<b>',
'B', 'HTML', 'Easy'),

('Which tag is commonly used to make text italic?',
'<italic>',
'<i>',
'<emphasis>',
'<it>',
'B', 'HTML', 'Easy'),

('Which tag represents emphasized text semantically?',
'<i>',
'<strong>',
'<em>',
'<italic>',
'C', 'HTML', 'Easy'),

('Which tag represents strong importance semantically?',
'<b>',
'<strong>',
'<important>',
'<bold>',
'B', 'HTML', 'Easy'),

('Which tag is used to define a section of navigation links?',
'<navigation>',
'<nav>',
'<navigate>',
'<links>',
'B', 'HTML', 'Easy'),

('Which tag represents the main content of a document?',
'<content>',
'<main>',
'<primary>',
'<section>',
'B', 'HTML', 'Easy'),

('Which tag is used to define a footer?',
'<bottom>',
'<footer>',
'<foot>',
'<end>',
'B', 'HTML', 'Easy'),

('Which tag is used to define a header section?',
'<top>',
'<header>',
'<headsection>',
'<heading>',
'B', 'HTML', 'Easy'),

('Which tag is used to define a generic section of content?',
'<section>',
'<part>',
'<content>',
'<divsection>',
'A', 'HTML', 'Easy'),

('Which tag is commonly used as a generic block-level container?',
'<container>',
'<div>',
'<block>',
'<box>',
'B', 'HTML', 'Easy'),

('Which tag is commonly used as a generic inline container?',
'<span>',
'<inline>',
'<text>',
'<label>',
'A', 'HTML', 'Easy'),

('Which attribute is used to assign a unique identifier to an element?',
'class',
'id',
'name',
'key',
'B', 'HTML', 'Easy'),

('Which attribute is used to assign one or more classes to an element?',
'id',
'style',
'class',
'group',
'C', 'HTML', 'Easy'),

('Which attribute can be used to apply inline CSS?',
'css',
'style',
'design',
'format',
'B', 'HTML', 'Easy'),

('Which tag is used to include an external JavaScript file?',
'<javascript>',
'<script>',
'<js>',
'<code>',
'B', 'HTML', 'Easy'),

('Which tag is used to link an external CSS file?',
'<css>',
'<style>',
'<link>',
'<stylesheet>',
'C', 'HTML', 'Easy'),

('Which attribute specifies the location of an external CSS file?',
'src',
'href',
'path',
'url',
'B', 'HTML', 'Easy'),

('Which HTML element is used to embed another webpage?',
'<frame>',
'<iframe>',
'<embedpage>',
'<web>',
'B', 'HTML', 'Medium'),

('Which attribute opens a hyperlink in a new browsing context?',
'target="_blank"',
'open="new"',
'new="true"',
'window="new"',
'A', 'HTML', 'Easy'),

('Which semantic HTML element is used for an independent piece of content?',
'<article>',
'<content>',
'<post>',
'<independent>',
'A', 'HTML', 'Medium');