INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('What does SQL stand for?',
'Structured Query Language',
'Simple Query Language',
'Standard Question Language',
'System Query Language',
'A', 'SQL', 'Easy'),

('Which SQL statement is used to retrieve data from a table?',
'GET',
'SELECT',
'FETCH',
'READ',
'B', 'SQL', 'Easy'),

('Which SQL statement is used to add new records to a table?',
'ADD',
'INSERT INTO',
'CREATE',
'APPEND',
'B', 'SQL', 'Easy'),

('Which SQL statement is used to modify existing records?',
'CHANGE',
'UPDATE',
'MODIFY',
'ALTER',
'B', 'SQL', 'Easy'),

('Which SQL statement is used to remove records from a table?',
'REMOVE',
'DELETE',
'DROP',
'CLEAR',
'B', 'SQL', 'Easy'),

('Which SQL clause is used to filter records?',
'FILTER',
'WHERE',
'SELECT',
'CONDITION',
'B', 'SQL', 'Easy'),

('Which clause is used to sort query results?',
'SORT BY',
'ORDER BY',
'GROUP BY',
'ARRANGE BY',
'B', 'SQL', 'Easy'),

('Which keyword sorts results in descending order?',
'DOWN',
'DESC',
'DESCENDING',
'REVERSE',
'B', 'SQL', 'Easy'),

('Which keyword sorts results in ascending order?',
'ASC',
'UP',
'ASCENDING',
'ORDER',
'A', 'SQL', 'Easy'),

('Which SQL clause groups rows having the same values?',
'GROUP BY',
'ORDER BY',
'COLLECT BY',
'COMBINE BY',
'A', 'SQL', 'Easy'),

('Which clause is used to filter grouped results?',
'WHERE',
'FILTER',
'HAVING',
'GROUP WHERE',
'C', 'SQL', 'Medium'),

('Which function returns the number of rows?',
'SUM()',
'COUNT()',
'NUMBER()',
'ROWS()',
'B', 'SQL', 'Easy'),

('Which function calculates the average value?',
'AVERAGE()',
'AVG()',
'MEAN()',
'CALCAVG()',
'B', 'SQL', 'Easy'),

('Which function returns the largest value?',
'MAX()',
'HIGHEST()',
'LARGE()',
'TOP()',
'A', 'SQL', 'Easy'),

('Which function returns the smallest value?',
'MIN()',
'LOWEST()',
'SMALL()',
'BOTTOM()',
'A', 'SQL', 'Easy');

INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('Which function calculates the total of numeric values?',
'SUM()',
'TOTAL()',
'ADD()',
'CALCULATE()',
'A', 'SQL', 'Easy'),

('Which keyword removes duplicate rows from a SELECT result?',
'UNIQUE',
'DISTINCT',
'DIFFERENT',
'ONLY',
'B', 'SQL', 'Easy'),

('Which operator is used to search for a pattern?',
'LIKE',
'MATCH',
'SEARCH',
'PATTERN',
'A', 'SQL', 'Easy'),

('Which wildcard represents any number of characters with LIKE?',
'_',
'%',
'*',
'#',
'B', 'SQL', 'Easy'),

('Which wildcard represents exactly one character with LIKE?',
'%',
'_',
'*',
'?',
'B', 'SQL', 'Easy'),

('Which operator checks whether a value is within a range?',
'RANGE',
'BETWEEN',
'WITHIN',
'INRANGE',
'B', 'SQL', 'Easy'),

('Which operator checks whether a value matches any value in a list?',
'BETWEEN',
'IN',
'MATCH',
'ANYWHERE',
'B', 'SQL', 'Easy'),

('Which operator is used to combine two conditions where both must be true?',
'OR',
'AND',
'BOTH',
'&&',
'B', 'SQL', 'Easy'),

('Which operator is used when at least one condition must be true?',
'AND',
'OR',
'EITHER',
'||',
'B', 'SQL', 'Easy'),

('Which keyword is used to give a column or table a temporary name?',
'NAME',
'AS',
'ALIAS',
'RENAME',
'B', 'SQL', 'Easy'),

('Which SQL command is used to create a new table?',
'NEW TABLE',
'CREATE TABLE',
'MAKE TABLE',
'BUILD TABLE',
'B', 'SQL', 'Easy'),

('Which SQL command is used to change the structure of an existing table?',
'UPDATE',
'ALTER TABLE',
'CHANGE TABLE',
'MODIFY TABLE',
'B', 'SQL', 'Easy'),

('Which SQL command permanently removes a table?',
'DELETE TABLE',
'REMOVE TABLE',
'DROP TABLE',
'CLEAR TABLE',
'C', 'SQL', 'Easy'),

('Which constraint uniquely identifies each row in a table?',
'UNIQUE KEY',
'PRIMARY KEY',
'IDENTIFIER',
'ROW KEY',
'B', 'SQL', 'Easy'),

('Which constraint prevents duplicate values in a column?',
'PRIMARY',
'UNIQUE',
'DISTINCT',
'CHECK',
'B', 'SQL', 'Easy');

INSERT INTO coding_questions
(question, optiona, optionb, optionc, optiond, answer, category, difficulty)
VALUES

('Which constraint is used to ensure a column cannot contain NULL values?',
'NOT NULL',
'NO NULL',
'REQUIRED',
'CHECK NULL',
'A', 'SQL', 'Easy'),

('Which constraint is used to enforce a condition on column values?',
'VALIDATE',
'CHECK',
'CONDITION',
'RULE',
'B', 'SQL', 'Medium'),

('Which constraint is used to create a relationship between two tables?',
'CONNECT',
'FOREIGN KEY',
'REFERENCE KEY',
'LINK KEY',
'B', 'SQL', 'Easy'),

('Which SQL keyword is used to combine rows from two or more tables?',
'COMBINE',
'JOIN',
'MERGE',
'CONNECT',
'B', 'SQL', 'Easy'),

('Which JOIN returns only matching rows from both tables?',
'LEFT JOIN',
'RIGHT JOIN',
'INNER JOIN',
'FULL JOIN',
'C', 'SQL', 'Easy'),

('Which JOIN returns all rows from the left table and matching rows from the right table?',
'INNER JOIN',
'RIGHT JOIN',
'LEFT JOIN',
'FULL JOIN',
'C', 'SQL', 'Easy'),

('Which JOIN returns all rows from the right table and matching rows from the left table?',
'LEFT JOIN',
'RIGHT JOIN',
'INNER JOIN',
'CROSS JOIN',
'B', 'SQL', 'Easy'),

('Which JOIN returns all matching and non-matching rows from both tables?',
'INNER JOIN',
'LEFT JOIN',
'RIGHT JOIN',
'FULL OUTER JOIN',
'D', 'SQL', 'Medium'),

('Which JOIN produces every possible combination of rows from two tables?',
'INNER JOIN',
'CROSS JOIN',
'FULL JOIN',
'COMBINE JOIN',
'B', 'SQL', 'Medium'),

('Which keyword is used to combine the results of two SELECT statements and remove duplicates?',
'COMBINE',
'UNION',
'MERGE',
'JOIN',
'B', 'SQL', 'Easy'),

('Which keyword combines SELECT results while keeping duplicate rows?',
'UNION',
'UNION ALL',
'ALL UNION',
'MERGE ALL',
'B', 'SQL', 'Medium'),

('Which SQL statement is used to change data in an existing row?',
'UPDATE',
'ALTER',
'CHANGE',
'MODIFY',
'A', 'SQL', 'Easy'),

('Which SQL statement is used to remove all rows while keeping the table structure?',
'DELETE',
'DROP',
'TRUNCATE',
'REMOVE',
'C', 'SQL', 'Medium'),

('Which command is used to permanently remove a database?',
'DELETE DATABASE',
'DROP DATABASE',
'REMOVE DATABASE',
'CLEAR DATABASE',
'B', 'SQL', 'Easy'),

('Which SQL keyword is used to give a temporary name to a table or column?',
'AS',
'NAME',
'LABEL',
'ALIAS',
'A', 'SQL', 'Easy'),

('Which SQL clause is commonly used with aggregate functions to group rows?',
'ORDER BY',
'GROUP BY',
'HAVING BY',
'COLLECT BY',
'B', 'SQL', 'Easy'),

('Which SQL function returns the number of non-NULL values in a column?',
'COUNT()',
'NUMBER()',
'COUNTA()',
'TOTAL()',
'A', 'SQL', 'Medium'),

('Which SQL keyword is used to check for missing values?',
'IS NULL',
'EQUAL NULL',
'NULL CHECK',
'HAS NULL',
'A', 'SQL', 'Easy'),

('Which operator means "not equal to" in SQL?',
'<>',
'!=',
'Both A and B',
'NOT=',
'C', 'SQL', 'Easy'),

('Which SQL command is commonly used to save a transaction permanently?',
'SAVE',
'COMMIT',
'STORE',
'CONFIRM',
'B', 'SQL', 'Medium');